language: bash
python: '3.6'
notifications:
  slack:
    rooms:
      - secure: 0i8d+2vWq1vjEHP5QkHUR/ovCmsr3083GocWDURAspSsLJCYGFgMWPYXn2LS1yLq8CD991hxuPrNmHKDX6l+pQwxXlQPAH22Sgq4yw9JEbR2Dsfo6taqCe4eMUvmZkJ8Q2U/hzy0y7eVPc1XfqkW+I9+/npxAsFPSDCQZRQe4LtQJ8VfB927vmiTVs4a/NcfYtBMHSJs4SrlnrO6NoGZFbzQYPkTdYNHG489Ipw1mkyRdLYp8aZtw485GJXD1sv52C8upqf52fX/Dj7WAApl27BImo0vwUXAuJyDIm5RY5MsV2KPZpB3R2gq43taSZxZ15R/Nox6ppfsz8SkcKalpGFP0l7bJyN4bfNZM/5J2Gu9l3lQlAt2n//xWzyEyNSg0YJ0m/XT6BhSzTaRDm+K8uGO8lzMTpec5to6gnSD9ngJ8qM92TRszHL+vryyDnBF22t+tpv4sktVSAZP0S6Ay1dLIXgO0rm4tm2C+daccTJXX62NGvVxPZCL+GFdNBEFr6/8+/HXkKd7YoF+4vcmEIlJLuz4bKqKWF93P+EpzOliKSJZlfsx1/4Gz68bhXl9QTtfdX7JfAdOEWZ6aWUmgrpyStplThXTtLD4+4pPifu1z+iF9mbSo3XFXPX/hbvFqJtr7AM/5nHSTxsl5TQsBS8nzxP7dCGSSh44bEcVxvU=
