language: bash
python: '3.6'
notifications:
  slack:
    rooms:
      secure: ERW4l3iApBHqyUE49ji/PbmBQa3/Fxfkdqtj1CBUKu/2Fbi9hPpLxeEnus8EzTAtzgYB3bBTIQ/DHWHtsrlPeI/ULRinYWxxO6LMebTRnsvq1C68UOfOUTnMxuPuN3bErrT28zI7b039/uJQlmeoCyQNALni1LCUrvHeLLumbkujCAD53g8RehnT29q2OStWQ3a7CFZDP/MZQo+/SkagSeWzlqlGvVqwWuztT6U9cCD1wrzs990K3w1k+d7TOYZhqoYdDEGhWUJKZKTLhR30T6EYK7QA4jF3+6suSGt4//Z8MyrTFVqD2ua2OtYXA5ivOdqh58ML2UQ4ED7Hw7xTwymANOejxxpxQJajNTUkeAeW8UIY+g51CqkhOswLWtBgd9lclNM5b6vrB3wUrIM05uSVTEm7o/PE4/rYtenoOHE1z/++j6Ymhb76MdP0VvPywYiOcwhWw9i/yyyiKrVZTHr6AbGRRN2FVu7UF7w5yw9KIwUHT4IGz2iXaFO6mVTGaesNQeNe3bELRaEmDLSbFdmoqRDpUXLCWTtr34cDJ30twnJbJgQC714hJbYYujnKjIjzrbgNt8DS7jydmc92PgHX9V+yaroZxWX3dj6+6gnpe1OweCNGVcYoZfIQEyeFr+0HEuCUXXLIBP7LDx3aWWKbe53zUabZ0Siy3MncwkE=
