---
language: python
python: "3.6"

services:
  - docker

install:
  - pip install ansible>=2.4 molecule>=2.6 pytest-testinfra docker

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  email: false
  slack:
    rooms:
      - secure: PIsWcgodAdJSSTunVdIl2U2zXz+gJFvF4X4K8fMdZrd0vlvK7XtVHya2CLFZVa3q2Ao3fysl9ivau1bBZOCXZDaCKnaNJcCW1ler4wn9qaeAowRq2TCJZbg8MeIzP37b6+4x6SaVNYov0SNuBiXCN5W0GKzTmYT5GfFHPTG5LTNtssIeLjQ7RZwSx8YBv11aTmzV+dqD91L/z2d9526BdNAXjmqSDkwlwSUw+IdsHzsJkzJBgVsOhCTUNZpwOS0/oeL9e4uDxrPQNijaV9zhEN8qnNyUdtHvyHrXQS9rW1wbX3nlJwY7SpyFGEeTt21atTl6+qEOkZyQwwwgJs2nsesb++XabeHhzxlC1ZZholglZiLig9v2EuN3/YELqSw89Y7t8ucJDsXXJaJ5FvvCngUMboRxUBXDmNtlqG2qu5HHkmVwA6OlGHRcchQD9cD9+iXdv8ux/35Nyq4XzlwKcwjOLpKXzYapwkp8XMqo869klaq7gT3LRsAh9Z3gvnnGqjF25mK0/zBZyM5SKeTL07IyRtI+wqDgPaZY93T1m+UtffXCmUYTJqYTGgJ7ITTICz3r3XQd+p+lRrsCIkQC8twCi3Cn34r3TcCtm5uaFW6j7hPM2hlYT8gglJ4/N8eIv0coD1GQHaCevDmqUGxutLpzal/mdQOabIzx2ZSIoB4=
      