language: bash
python: '3.6'
notifications:
  slack:
    rooms:
      secure: ukXZTJc+YL1zCuVruO8dglpGsiQUHKNcVOitT8IZZzd5D5EtH761WTEolrJ/lvfaGupy9ARqr5gQtcqWn/I0GCXiQaC/Lna/juu3HkTo1kgC1AuNf1+4YRjdVWk9bJFBIrS6GuRS7J/HqMVZHmwpkphdeoOSbZOvJ5AJFJZfdvBUUxXJFouJ2S1u05Fn0y6laodZpoNrzQIw/GVijrM0kBMl9DeGLSg+K8paLC9ENJ5Ps91MbuRMtCKM9RXPSOSHqyU/jbaHVgJmXm4DluG654NPTvZvBRbhV/PkcElB8G6ls8jkqtW/93XOahmQsv5FnPRE2iEfmeg9kwW231pqK9uS8A8TVPB38NqbAGStUK4aySJ6enOKISG3UFlDnIrKfp/0B2nFuO9x+vbwpnatsR9N7xT7LBfKGjw/ajt6YqsgYKlvUQcRC1wel5dVi8lY7beb5FUH7eeBExNkMku5ViCqpPgks1SBJXlmVYMKgLvhk/Qko92AUO+6W0e76+5NOSvPHNt2dGncOJIVc5G3++E90kR8RrFqQZVAr/5cxR8+q9Nt70WMH+9i8MjaLzxqhzU4QrJB1gO2RKHWVonSxVMvLvjTCq6n1uY8yp+RKZvX3o2DCyOZraEnghjab8SqKoDn6X56T35OP4mCRVAceFYqRCt2OerCgaRtnJ/t8Ds=
