language: python
python: '3.6'
services:
- docker
install:
- pip install ansible>=2.4 molecule>=2.6 pytest-testinfra molecule-docker
script:
- molecule --version
- ansible --version
- molecule test
notifications:
  email: false
  slack:
    secure: UreUkcWn+sJM7+Ryoff7ldAPKQRXNbZWKn0g2kCGb2BEZiH+HjWUioHuJRcEh7+Qvy1Ytx5WlS4XH8CGIn7nZ4/2onwsQFDamOTaDkQj/QqrzXg8uB6jpU2SXDR7DmsZ4ly4CtO9dBMtEcIw/xSQC6uEV7Lq9pKh/E+JSw/zxlBhra9DuwyfEv93OkCs0gEdW9ep94hjXwCaw4kGk8mt1xlwfiITDZwV1Q5xZSQXA7/HOqgli8BHI7Cngf0odZctrcrZ0SAioIwP92Fq5jIRTyqxJqcxU9oxjwZv7zwJRtXzJVw3eQXBF0MFNduUIOaK28JEHsyfxwd4uRWBw5KzzekUDZgVJbxBjCt/k36uT32FqVdfpB7lIac1BOS8MO5c+Dmgf62ZGW/yor47mi9O/Ql67gFD9UEakhHlwST0cTEKeKc2dDori1c5kNfiFljLIJxEdDVhCm08g5nKWRUFYpIWhtgGXXLjNgHjJKhnq6Jr/KqlOqxDnSOo9tyvAOE/oj2jMjRxNIP5gU4WU3KfN18g8cxYnWBlp9cB09ByILhDYV9C6A+/074QRwqeNqrzBDtuk+Lc4WAbD3p0LcLsWZ2TtiJOmi5Z0TzzDN0V7xxteXNIUEiLgkCsPeOYW3nF0aMoGe9JGJE++o2ZBYH3ZvDUx4u6jbrfNKlR0c7cBoU=
    on_success: always
    on_failure: always
    