---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # image: ubuntu:xenial
    image: barmank32/sys-ubuntu-py3:xenial 
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
